name: Security Analysis (SAST)

on: [push, pull_request]

jobs:
  bandit-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r . -x unit_tests/,integration_tests/
